SELECT A.AUTHOR_ID, A.AUTHOR_NAME,B.CATEGORY,SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B, (SELECT BOOK_ID,SUM(SALES) SALES
FROM BOOK_SALES 
WHERE DATE_FORMAT(SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY BOOK_ID) BS, AUTHOR A
WHERE B.BOOK_ID = BS.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID,B.CATEGORY
ORDER BY A.AUTHOR_ID,B.CATEGORY DESC


