SELECT C.AUTHOR_ID, C.AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM (
    SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
    ) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID
GROUP BY 1,3
ORDER BY 1,3 DESC