SELECT B.AUTHOR_ID,A.AUTHOR_NAME ,B.CATEGORY,SUM(BS.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY B.CATEGORY,A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC , B.CATEGORY DESC