SELECT A.ID AS ID, IF(CHILD_COUNT IS NULL, 0, CHILD_COUNT) AS CHILD_COUNT

FROM ECOLI_DATA AS A LEFT OUTER JOIN 
(SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
FROM ECOLI_DATA
GROUP BY PARENT_ID) AS B
ON A.ID = B.PARENT_ID
ORDER BY ID ASC;