SELECT YEAR(SALES_DATE) AS YEAR,MONTH(SALES_DATE) AS MONTH,GENDER, COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID AND GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3