WITH RECURSIVE GEN AS (

    SELECT D.ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA D
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT D.ID, D.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA D INNER JOIN GEN ON GEN.ID = D.PARENT_ID
)

SELECT
COUNT(*) AS COUNT
, G1.GENERATION
FROM GEN G1
LEFT JOIN GEN G2 ON G1.ID = G2.PARENT_ID
WHERE G2.ID IS NULL
GROUP BY G1.GENERATION