SELECT A.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT)*PRICE TOTAL_SALES
FROM FOOD_ORDER A JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY A.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC
