WITH A AS (
SELECT A.FLAVOR,  A.TOTAL_ORDER + B.TOTAL_ORDER AS TOTAL
FROM FIRST_HALF A JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
ORDER BY TOTAL DESC
LIMIT 3
)

SELECT FLAVOR
FROM A

    