-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT  *
    FROM APPOINTMENT
    WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS'
     ) A JOIN PATIENT B ON A.PT_NO = B.PT_NO 
        JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
ORDER BY APNT_YMD;