SELECT U.USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER U JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = "DONE"
GROUP BY WRITER_ID) BOARD ON BOARD.WRITER_ID = U.USER_ID
WHERE TOTAL_SALES>=700000
ORDER BY 3