-- 코드를 작성해주세요
WITH SCORETABLE AS (
    SELECT EMP_NO, SUM(SCORE)/2 AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT S.EMP_NO AS EMP_NO,EMP_NAME,(
    CASE  WHEN SCORE >= 96 THEN "S" WHEN SCORE >=90 THEN "A" WHEN SCORE >=80 THEN "B"
    ELSE "C" END
) AS GRADE, ( CASE WHEN SCORE >= 96 THEN SAL*0.2 WHEN SCORE >=90 THEN SAL*0.15
    WHEN SCORE >=80 THEN SAL*0.1 ELSE 0 END
    ) AS BONUS
FROM HR_EMPLOYEES HE JOIN SCORETABLE S ON HE.EMP_NO = S.EMP_NO
ORDER BY EMP_NO;
