-- 코드를 입력하세요
select M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,"%Y-%m-%d")
from MEMBER_PROFILE M JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID 
where M.MEMBER_ID = (
    SELECT R.MEMBER_ID  
    from REST_REVIEW R
    group by R.MEMBER_ID
    order by SUM(R.REVIEW_SCORE) DESC
    limit 1
)
ORDER BY R.REVIEW_DATE , R.REVIEW_TEXT
    
