WITH A AS ( SELECT SUM(CODE) CODE
    FROM SKILLCODES
    WHERE NAME = "Python" or NAME = "C#") 

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE EXISTS (
    SELECT 1
    FROM A
    WHERE CODE & SKILL_CODE 
)
ORDER BY 1;