WITH MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR1 ,MAX(SIZE_OF_COLONY) SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
    (SELECT SIZE
    FROM MAX_SIZE 
    WHERE YEAR1 = YEAR) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY 1, 2



