-- 코드를 입력하세요
SELECT DISTINCT(A.CAR_ID)
from CAR_RENTAL_COMPANY_CAR A join CAR_RENTAL_COMPANY_RENTAL_HISTORY B on A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = "세단" AND MONTH(B.START_DATE)='10'
ORDER BY A.CAR_ID DESC;