WITH MAX_VIEWS AS(
    SELECT *
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (
                SELECT MAX(VIEWS)
                FROM USED_GOODS_BOARD
                )
)

SELECT CONCAT("/home/grep/src/",A.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) FILE_PATH
FROM MAX_VIEWS A JOIN USED_GOODS_FILE  B ON A.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC;


