SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME

FROM (
    SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
    ,RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) P
    FROM FOOD_PRODUCT A
    WHERE CATEGORY IN ('과자','국','김치', '식용유')
    ) A
WHERE P =1 
ORDER BY 2 DESC