WITH A AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),B AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),C AS (
    SELECT SUM(CODE) CODE 
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT GRADE, ID, EMAIL
FROM (
    SELECT (CASE
            WHEN SKILL_CODE & (SELECT * FROM A) && SKILL_CODE & (SELECT * FROM C)  THEN 'A'
            WHEN SKILL_CODE & (SELECT * FROM B) THEN 'B'
            WHEN SKILL_CODE & (SELECT * FROM C) THEN 'C'
        END
    )  AS GRADE, ID, EMAIL
    FROM DEVELOPERS 
    ) A
where GRADE IS NOT NULL
ORDER BY GRADE, ID
